# Use a imagem do Node.js como base
FROM node:14

# Defina o diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copie os arquivos de dependência do projeto
COPY backend/package*.json ./

# Instale as dependências
RUN npm install

# Copie os arquivos do projeto para o contêiner
COPY backend/ .

# A porta que sua aplicação backend escuta (ajuste se necessário)
EXPOSE 3000

# Comando para iniciar o aplicativo
CMD [ "node", "index.js" ]
