name: Build and Deploy to GKE

on:
  push:
    branches:
      - master # Sua branch de produção
  
jobs:
  set-build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Install gcloud plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
  
    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGISTRY_HOSTNAME }}

    - name: Build and push Docker images
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prj-contaja-prd/repo-prod:${{ github.sha }} ./backend
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prj-contaja-prd/repo-prod:${{ github.sha }}
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prj-contaja-prd/repo-prod:${{ github.sha }} ./frontend
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prj-contaja-prd/repo-prod:${{ github.sha }}
